// Generated by Wrangler on Thu Aug 29 2024 20:12:48 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	AI: Ai;
	DB: D1Database;
	SESSIONS: KVNamespace;
	JWT_SECRET: string;
	// KV binding for static assets (automatically added by Workers Sites)
	__STATIC_CONTENT: KVNamespace;
	__STATIC_CONTENT_MANIFEST: string;
}
